experiment:
  name: weeddetection-rededge
  group: SplitLawin
  continue_with_errors: True
  start_from_grid: 0
  start_from_run: 0
  tracking_dir: null
  entity: pasqualedem
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [cross_entropy]
      params:
        weight: [[0.0638, 1.0, 1.6817]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss]
    freeze_pretrained: [True]

  early_stopping:
    enabled: [True]
    params:
      patience: [10]
      monitor: [loss]
      mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
    f1:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
  test_metrics:
    jaccard:
      num_classes: [3]
    auc:
      num_classes: [3]
    conf_mat:
      num_classes: [3]
    f1:
      num_classes: [3]
      average: [macro]
      mdmc_average: [global]
    precision:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    recall:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [splitlaweed]
    params:
      backbone: [MiT-B0]
      backbone_pretrained: [True]
      main_channels: [3]
      side_pretrained: ['G']
      fusion_type: ['conv_sum', 'conv_sum_drop']

  dataset:
    root: ["dataset/0_rotations_processed_003_test/RedEdge"]
    train_folders: [['000', '001', '002', '004']]
    test_folders: [['003']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'B', 'NIR'], ['R', 'G', 'B', 'NDVI'], ['R', 'G', 'B', 'RE'], ['R', 'G', 'B', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  run_params:
    batch_size: [24]
    run_folders: [["007"]]


other_grids:
  -
    tags: [[]]
    train_params:
      freeze_pretrained: [True]
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]