experiment:
  name: weedmapping-rededge
  group: SplitLawin
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  tracking_dir: null
  logger: wandb
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [ focal ]
      params:
        gamma: [ 2.0 ]
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss]
    freeze_pretrained: [True]

  early_stopping:
    patience: [10]
    monitor: [loss]
    mode: [min]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [3]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [wd/models/splitlawin]
    params:
      backbone: [MiT-B0, MiT-B1]
      backbone_pretrained: [True]
      main_channels: [3]
      fusion_type: [conv_sum, conv_sum_drop, squeeze_excite]
      side_pretrained: [null]

  dataset:
    root: ["dataset/0_rotations_processed_003_test/RedEdge"]
    train_folders: [['000', '001', '002', '004']]
    test_folders: [['003']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'B', 'NIR'], ['R', 'G', 'B', 'NDVI'], ['R', 'G', 'B', 'RE'], ['R', 'G', 'B', 'NIR', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4, 16]]

other_grids:
