experiment:
  name: weeddetection
  group: RR_007_test
  continue_with_errors: False
  start_from_grid: 0
  start_from_run: 0
  tracking_dir: null
  entity: pasqualedem
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [cross_entropy]
      params:
        weight: [[0.0273, 1.0, 4.3802]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss]
    freeze_pretrained: [True, False]

  early_stopping:
    enabled: [True]
    params:
      patience: [10]
      monitor: [loss]
      mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
    f1:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
  test_metrics:
    jaccard:
      num_classes: [3]
    conf_mat:
      num_classes: [3]
    f1:
      num_classes: [3]
      average: [macro]
      mdmc_average: [global]
    precision:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    recall:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]

  model:
    name: [wd/models/lawin/lawin]
    params:
      backbone: [MiT-B0, MiT-B1]
      backbone_pretrained: [True]

  dataset:
    root: ["dataset/4_rotations_processed_007_test/Sequoia"]
    train_folders: [['005', '006']]
    test_folders: [['007']]
    hor_flip: [True]
    ver_flip: [True]
    # channels: ['CIR', ['G', 'NDVI', 'NIR', 'R', 'RE']]
    # channels: [['R', 'G'], 'CIR', ['R', 'G', 'RE', 'NIR'], ['G', 'NDVI', 'NIR', 'R', 'RE']]
    # channels: [['R', 'G', 'RE', 'NIR']]
    # channels: [['R', 'G']]
    channels: [['R', 'G'], ['NDVI'], 'CIR']
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  run_params:
    batch_size: [24]
    run_folders: [["007"]]


other_grids:
  -
    tags: [[rotation]]
    train_params:
      freeze_pretrained: [True, False]
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]