experiment:
  name: weeddetection
  group: Laweed
  continue_with_errors: True
  start_from_grid: 3
  start_from_run: 1
  tracking_dir: null
  entity: pasqualedem
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  # train, test, inference
  # phases: [[run]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [cross_entropy]
      params:
        weight: [[0.0273, 1.0, 4.3802]]
    # ema: True
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss]
    freeze_pretrained: [True, False]

  early_stopping:
    enabled: [True]
    params:
      patience: [10]
      monitor: [loss]
      mode: [min]

  train_metrics:
    jaccard:
      num_classes: [3]
    f1:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
  test_metrics:
    jaccard:
      num_classes: [3]
    auc:
      num_classes: [3]
    conf_mat:
      num_classes: [3]
    f1:
      num_classes: [3]
      average: [macro]
      mdmc_average: [global]
    precision:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    recall:
      average: [macro]
      num_classes: [3]
      mdmc_average: [global]
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [wd/models/laweed]
    params:
      backbone: [MiT-B0]
      backbone_pretrained: [True]
      main_channels: [1]
      main_pretrained: [['G']]
      side_pretrained: [null]

  dataset:
    root: ["dataset/4_rotations_processed_005_test/Sequoia"]
    train_folders: [['006', '007']]
    test_folders: [['005']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['NDVI']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  run_params:
    batch_size: [24]
    run_folders: [["007"]]


other_grids:
  -
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]
  -
    model:
      params:
        main_pretrained: [null]
  -
    model:
      params:
        main_pretrained: [null]
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]
  # CIR
  -
    model:
      params:
        main_channels: [3]
        main_pretrained: [null]
    dataset:
      channels: ['CIR']
  -
    model:
      params:
        main_channels: [3]
        main_pretrained: [null]
    dataset:
      channels: ['CIR']
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]
  -
    model:
      params:
        main_channels: [3]
        main_pretrained: [['G', 'G', 'R']]
    dataset:
      channels: ['CIR']
  -
    model:
      params:
        main_channels: [3]
        main_pretrained: [['G', 'G', 'R']]
    dataset:
      channels: ['CIR']
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]
  # R G NIR RE
  -
    model:
      params:
        main_channels: [4]
        main_pretrained: [['R', 'G', 'G', 'G']]
    dataset:
      channels:  [["R", "G", "NIR", "RE"]]
  -
    model:
      params:
        main_channels: [4]
        main_pretrained: [['R', 'G', 'G', 'G']]
    dataset:
      channels: [["R", "G", "NIR", "RE"]]
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]
  # R, G
  -
    model:
      params:
        main_channels: [2]
        main_pretrained: [null]
    dataset:
      channels: [['R', 'G']]
  -
    model:
      params:
        main_channels: [2]
        main_pretrained: [null]
    dataset:
      channels: [['R', 'G']]
    tags: [[]]
    train_params:
      loss:
        name: [ focal ]
        params:
          gamma: [ 2.0 ]