experiment:
  name: weedmapping-sequoia
  group: SplitLawin
  continue_with_errors: True
  start_from_grid: 0
  start_from_run: 0
  tracking_dir: null
  logger: wandb
  entity: null
  excluded_files: "*.pth"

parameters:
  tags: [[]]
  phases: [[train, test]]
  dataset_interface: [wd/data/WeedMapDatasetInterface]

  train_params:
    max_epochs: [500]
    initial_lr: [0.0001]
    optimizer: [Adam]
    optimizer_params:
      weight_decay: [0]
    loss:
      name: [ focal ]
      params:
        weight: [[0.0638, 1.0, 1.6817]]
        gamma: [ 2.0]
    seed: [42]
    zero_weight_decay_on_bias_and_bn: [True]
    average_best_models: [False]
    greater_metric_to_watch_is_better: [False]
    metric_to_watch: [loss]
    freeze_pretrained: [True, False]

  early_stopping:
    patience: [10]
    monitor: [loss]
    mode: [min]

  train_metrics:
    f1: &metric_params
      num_classes: &num_classes [3]
  test_metrics:
    jaccard: *metric_params
    conf_mat: *metric_params
    auc: *metric_params
    f1: *metric_params
    precision: *metric_params
    recall: *metric_params
    perclassauc:
      discriminator: # To discriminate between different classes
        [[
          ['auc_background', 0],
          ['auc_crop', 1],
          ['auc_weed', 2]
        ]]

  model:
    name: [wd/models/splitlawin]
    params:
      backbone: [MiT-B0, MiT-B1]
      backbone_pretrained: [True]
      main_channels: [2]
      fusion_type: ['conv_sum', 'conv_sum_drop', 'squeeze_excite']
      side_pretrained: ['G']

  dataset:
    root: ["dataset/4_rotations_processed_005_test/Sequoia"]
    train_folders: [['006', '007']]
    test_folders: [['005']]
    hor_flip: [True]
    ver_flip: [True]
    channels: [['R', 'G', 'NIR', 'RE'], ['R', 'G', 'NIR'], ['R', 'G', 'NDVI'], ['R', 'G', 'RE']]
    batch_size: [6]
    val_batch_size: [12]
    test_batch_size: [12]
    num_workers: [0]
    num_classes: [3]
    return_path: [True]
    size: [same]
    crop_size: [same]

  test_callbacks:
    PerExampleMetricCallback:
      phase: [TEST_BATCH_END]
    SegmentationVisualizationCallback:
  val_callbacks: 
    SegmentationVisualizationCallback: 
      batch_idxs: [[4, 16]]

other_grids:
